name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Activa el despliegue automático cuando haces push a la rama main.

# Otorga los permisos necesarios a GitHub Actions
permissions:
  contents: read
  pages: write
  id-token: write

# Permite solo un despliegue a la vez
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
      
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Instalar dependencias
        run: npm ci
        
      - name: Construir el proyecto
        run: npm run build
        
      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4
        
      - name: Subir artefacto (dist)
        uses: actions/upload-pages-artifact@v3
        with:
          # Subiremos la carpeta 'dist' que Vite crea por defecto
          path: './dist'
          
      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
